workflows:
  build-android:
    name: Build Android APK
    description: Build release APK for the project extracted from your upload
    max_build_duration: 60
    environment:
      flutter: stable
      vars:
        # If you want Codemagic to decode and use a keystore provided as base64:
        ANDROID_KEYSTORE_BASE64:
          encrypted: false
        ANDROID_KEYSTORE_PASSWORD:
          encrypted: false
        ANDROID_KEY_ALIAS:
          encrypted: false
        ANDROID_KEY_PASSWORD:
          encrypted: false
    scripts:
      - name: Setup keystore (if provided)
        script: |
          set -e
          if [ -n "$ANDROID_KEYSTORE_BASE64" ]; then
            echo "$ANDROID_KEYSTORE_BASE64" | base64 --decode > android/app/key.jks
          fi
      - name: Get dependencies
        script: flutter pub get
      - name: Pre-build info
        script: |
          echo "App package: com.example.app"
          echo "App name: jama3ti_app"
          echo "Version: 1.0.0+1"
      - name: Build release apk
        script: flutter build apk --release --no-shrink
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
   
